
server:
  port: 8070

spring:
  profiles:
    include:
      eureka,zipkin
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:8201/ # 指定了 Zipkin 服务器的地址

zuul:
  routes:
    web:
      path: /web/**
      serviceId: web-client
    #/api-b/ 开头匹配到service-producer
#    api-b:
#      path: /api-b/**
#      serviceId: service-producer
    #匹配/github/直接重定向到https://github.com/
    baidu:
      path: /baidu/**
      url: https://www.baidu.com/
