# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://192.168.133.129:8010/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
spring:
  main:
    allow-bean-definition-overriding: true #zipkin有重名的包 覆盖下